name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Confirm Deployment
        run: echo "CD Pipeline triggered at $(date). Image deployed from Docker Hub."
